server:
  port: 9000
spring:
  main:
    web-application-type: reactive
  application:
    name: apigateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true

