#server.port=8085
#spring.datasource.url=jdbc:mysql://localhost:3306/userdb
#spring.datasource.username=root
#spring.datasource.password=Sahasiem7#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: Sahasiem7#
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: auth-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true


