#server.port=8083
#spring.data.mongodb.database=userdb
#spring.data.mongodb.uri=mongodb://localhost:27017/
#server.error.include-message=always

server:
  port: 8083
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/moviedb
  application:
    name: user-movie-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true

